http:
  port: 8081 #http访问端口
server:
  port: 443 #服务器访问端口
  ssl:
    key-store: classpath:lin.pfx  #配置ssl证书
    key-store-password: 04R3ihy1  #配置密码
    key-store-type: PKCS12  #HTTPS证书转换成PEM格式
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.106.130.68:3306/yiCai?characterEncoding=utf-8&useSSL=false
    username: root
    password: zhangxuelin..123
#    经得住阿里考验的 连接池 并且 有监控功能
    druid:
      initialSize: 5 #初始化时建立物理连接的个数
      minIdle: 5 #最小连接池数量
      maxActive: 20 #最大连接池数量
      maxWait: 60000 #获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
      timeBetweenEvictionRunsMillis: 60000 #配置间隔多久才进行一次检测 检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 300000 #只知道这个参数是和逐出线程有关的
      stat-view-servlet:
        enabled: true #开启监控
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
    host: 39.106.130.68
    port: 6379
    password: zhangxuelin..123
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    use-actual-param-name: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#日志  将系统运行的日志,记录到对应的位置,上线的时候  在改tomcat的 server.xml路径
#logging:
#  pattern:
#    console: "%d-%msg%n"
#  path: C:\11\
#  file: C:\11\log.log